@startuml
entity 社員情報マスタ {
  id(PK)
  --
  Name
  Birth
  DepartmentId(FK)
}
entity 部署情報マスタ {
  id(PK)
  --
  Name
  Description
}
entity 学歴マスタ {
id(PK)
--
employeeId(FK)
SchoolName
Type
}

entity 社内サークルメンバテーブル {
  id({PK)
  --
  CirculeName
  employeeId(FK)
}

社員情報マスタ }|-l-|| 部署情報マスタ
社員情報マスタ ||-r-|{ 学歴マスタ
社員情報マスタ ||-d-o{ 社内サークルメンバテーブル
@enduml